### ISSUE TITLE
taro build --type weapp --blended error

### ISSUE THREAD

**Issue by vinurs** [NervJS/taro-blended#6]
无法编译，出现下面的错误
```
taro build --type weapp --blended

👽 Taro v3.2.1

/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/node_modules/resolve/lib/sync.js:81
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");
              ^

Error: Cannot find module '@tarojs/plugin-platform-alipay' from '/Users/vinurs/tmp/taro-blended/taro-project'
    at Function.resolveSync [as sync] (/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/node_modules/resolve/lib/sync.js:81:15)
    at /Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/utils/index.js:46:31
    at Array.map (<anonymous>)
    at Object.resolvePresetsOrPlugins (/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/utils/index.js:45:30)
    at Kernel.resolvePlugins (/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:90:36)
    at Kernel.initPresetsAndPlugins (/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:81:14)
    at Kernel.<anonymous> (/Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at /Users/vinurs/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by vinurs** [comment]
安装一下缺失的 `@tarojs/plugin-platform-alipay` 就可以了
